---
abstract: 'An object oriented interface to pacmd.'
author:
  - 'Evan Carroll.'
  - 'Evan Carroll <me@evancarroll.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PulseAudio
no_index:
  directory:
    - inc
    - t
requires:
  IPC::Run3: 0
  Moose: 2.0
  MooseX::Types: 0
  autodie: 0
  constant: 0
  perl: 5.10.0
resources:
  homepage: https://github.com/EvanCarroll/perl-pulseaudio
  license: http://dev.perl.org/licenses/
  repository: git://github.com/EvanCarroll/perl-pulseaudio.git
version: 0.02
